
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

output "frontend-service-cloud-run_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.frontend-service-cloud-run.service_uri
}
output "backend-service-cloud-run_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.backend-service-cloud-run.service_uri
}
output "memorystore_host" {
  description = "The IP address of the instance."
  value       = module.memorystore.host
}
output "memorystore_port" {
  description = "The port number of the exposed Redis endpoint."
  value       = module.memorystore.port
}
